osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: Q63YUw8V26YtWoYIMv6NtTi5U8kGnH6WDCKZl0iWI8akiy2K/NfmSJbr44uBewF+R2mOykKYs63C5uXrx+lbcaWrmIXTV88FBIEGTa61m3r+Oj3CBs22ZDq5XwmKFoNrNqWoMptF2mNja7xAqMwnPygTzv8/iLBUfZskXFxaOsPW/T5S56+LMew0OkM6pjkMiqcWs8RPhmAw8QXb4epPo4fErhaIPeKV8EXNbC/soD9xF8s77PF8UKsWvur1hjE6YzF/4OoTLleRNCCAO9FcP5F0zFRbyTWH75kiSJUl/Eh8UFoHPwm8kdeoyJ+0s53Y86r9LBNVY6zGxgXoeNFsUDyw2ls/ppi2/RmWfLMJ9/Maabjy24MSS/vKAyScz3UAk1M19pO1rKMeBGKGY8+7yQ5N/pr07ZJwCewPEFTmmgA5Af7s+NMN2JmkqISxOCUoglsXAIg8dkfLKCIhQsgvlvESDdQ3wAQWc43oOq8T7aO/2aWX97AFMJdYHJtHEG/fo/0jqXCPngPRG3hh2tmKabYSabGRmQ0nWdnE4UETmhge7LEnUWlJJxp1Mtls+HfgNuQYitHugNT07+UJXw3gyi8u/WVLoTj7OXPj4VANhMIX4r+SIfFVGyQZ7myV2YoBnrugyaCAd5mL7UyDLaCKdBkDiFsbGt3DIQxlx4fOEC0=

os:
  - linux
  - osx

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

addons:
  apt:
    packages:
      - libsecret-1-0

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn dist -- --mac --win; fi

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
